export const portfolios = [

  {
    image: "/folio-yoorix-pos.jpg",
    title: "Yoorix POS",
    description: `Hello demo lorem ipsum`,
    tags: ["Laravel", "Inertia-React", "Shadcn/UI"],
    link: "https://yoorix.store.com/",
  },
  {
    image: "/folio-yoorix-ecommerce.jpg",
    title: "Yoorix Ecommerce",
    description: `Hello demo lorem ipsum`,
    tags: ["Nuxt", "Bootstrap", "Context API"],
    link: "https://yoorix.com/",
  },
  {
    image: "/folio-bigshop.jpg",
    title: "1 BigShop E-commerce",
    description: `Hello demo lorem ipsum`,
    tags: ["Next", "Shadcn/UI", "Zustand"],
    link: "https://1-big-shop.vercel.app/",
  },
  {
    image: "/folio-13.png",
    title: "Happy Jolly E-commerce",
    description: `Hello demo lorem ipsum`,
    tags: ["Next", "Shadcn/UI", "Zustand"],
    link: "https://repliq-ecommerce-eight.vercel.app/",
  },
  {
    image: "/folio-10.png",
    title: "Verge Sourcing",
    description: `Hello demo lorem ipsum`,
    tags: ["Next", "Three.js", "Shadcn/UI"],
    link: "https://vergesourcing-client.vercel.app/",
  },
  {
    image: "/folio-11.png",
    title: "Sleek Portfolio",
    description: `Hello demo lorem ipsum`,
    tags: ["Next", "TailwindCSS", "Shadcn/UI"],
    link: "https://sleek-portfolio-alpha.vercel.app/",
  },
  {
    image: "/folio-12.png",
    title: "HonestElite [Social Media]",
    description: `Hello demo lorem ipsum`,
    tags: ["Next", "TailwindCSS", "Shadcn/UI"],
    link: "https://prod.honestelite.com",
  },
  {
    image: "/folio-9.png",
    title: "Imperial Legacy Inc.",
    description: `Hello demo lorem ipsum`,
    tags: ["Next", "TailwindCSS", "Shadcn/UI"],
    link: "https://imperial-legacy-client.vercel.app/",
  },
  {
    image: "/folio-8.png",
    title: "Rabeya Group ERP",
    description: `Hello demo lorem ipsum`,
    tags: ["React", "TailwindCSS", "Express"],
    link: "https://rabeya-group-frontend.vercel.app/",
  },
  {
    image: "/folio-7.png",
    title: "Bazaar E-commerce",
    description: `Hello demo lorem ipsum`,
    tags: ["Next", "React", "MUI"],
    link: "https://bazaar-ecommerce-dev.vercel.app/",
  },
  {
    image: "/folio-6.png",
    title: "Honest-Elite Dashboard",
    description: `Hello demo lorem ipsum`,
    tags: ["Next", "React", "MUI"],
    link: "https://honest-elite-dashboard.vercel.app/",
  },
  {
    image: "/folio-1.png",
    title: "Personal Portfolio",
    description: `Hello demo lorem ipsum`,
    tags: ["Next", "React", "MUI"],
    link: "https://hasibul-mahi.vercel.app/",
  },
  {
    image: "/folio-2.png",
    title: "Creative Learner",
    description: `Hello demo lorem ipsum`,
    tags: ["React", "Next", "MUI"],
    link: "https://hasibulmahi.github.io/Creative-Learner-By-Maxx/",
  },
  {
    image: "/folio-3.png",
    title: "Task Station",
    description: `Hello demo lorem ipsum`,
    tags: ["React", "Vue", "Tailwind"],
    link: "https://task-staion.vercel.app/",
  },
  {
    image: "/folio-4.jpg",
    title: "Weather Forecast",
    description: `Hello demo lorem ipsum`,
    tags: ["HTML", "CSS", "JavaScript"],
    link: "https://hasibulmahi.github.io/Weather-App/",
  },
  {
    image: "/folio-5.jpg",
    title: "Breweries Website",
    description: `Hello demo lorem ipsum`,
    tags: ["HTML", "CSS"],
    link: "https://hasibulmahi.github.io/Breweries-Website-Using-CSS-Grid/#breweries",
  },
];
