export const portfolios = [
  {
    image: "/folio-9.png",
    title: "Imperial Legacy Inc.",
    description: `Hello demo lorem ipsum`,
    tags: ["Next", "TailwindCSS", "Shadcn/UI"],
    link: "https://rabeya-group-frontend.vercel.app/",
  },
  {
    image: "/folio-8.png",
    title: "Rabeya Group ERP",
    description: `Hello demo lorem ipsum`,
    tags: ["React", "TailwindCSS", "Express"],
    link: "https://rabeya-group-frontend.vercel.app/",
  },
  {
    image: "/folio-7.png",
    title: "Bazaar E-commerce",
    description: `Hello demo lorem ipsum`,
    tags: ["Next", "React", "MUI"],
    link: "https://bazaar-ecommerce-dev.vercel.app/",
  },
  {
    image: "/folio-6.png",
    title: "Honest-Elite Dashboard",
    description: `Hello demo lorem ipsum`,
    tags: ["Next", "React", "MUI"],
    link: "https://honest-elite-dashboard.vercel.app/",
  },
  {
    image: "/folio-1.png",
    title: "Personal Portfolio",
    description: `Hello demo lorem ipsum`,
    tags: ["Next", "React", "MUI"],
    link: "https://hasibul-mahi.vercel.app/",
  },
  {
    image: "/folio-2.png",
    title: "Creative Learner",
    description: `Hello demo lorem ipsum`,
    tags: ["React", "Next", "MUI"],
    link: "https://hasibulmahi.github.io/Creative-Learner-By-Maxx/",
  },
  {
    image: "/folio-3.png",
    title: "Task Station",
    description: `Hello demo lorem ipsum`,
    tags: ["React", "Vue", "Tailwind"],
    link: "https://task-staion.vercel.app/",
  },
  {
    image: "/folio-4.jpg",
    title: "Weather Forecast",
    description: `Hello demo lorem ipsum`,
    tags: ["HTML", "CSS", "JavaScript"],
    link: "https://hasibulmahi.github.io/Weather-App/",
  },
  {
    image: "/folio-5.jpg",
    title: "Breweries Website",
    description: `Hello demo lorem ipsum`,
    tags: ["HTML", "CSS"],
    link: "https://hasibulmahi.github.io/Breweries-Website-Using-CSS-Grid/#breweries",
  },
];
